### ISSUE TITLE
Non exisiting /build/ folder

### ISSUE THREAD

**Issue by dgitaldesignco** [royboy789/Angular-Wordpress-Theme#16]
Thank you so much Roy for this theme will allow us to test and learn angular + wp!

Activated it. Got a few errors and found that /build/ folder doesn't exist in the theme but its coded into angular-enqueue.php

![screen shot 2015-09-17 at 9 28 19 pm](https://cloud.githubusercontent.com/assets/1154657/9951973/18b11392-5d83-11e5-93c6-231c3634f876.png)
![screen shot 2015-09-17 at 9 28 31 pm](https://cloud.githubusercontent.com/assets/1154657/9951972/18b0c1b2-5d83-11e5-8f53-bf3b1847e6d5.png)

**Comment by dgitaldesignco** [comment]
http://roysivan.com/angular-wordpress-theme/#/

Guess this github is not the same as the demo...had to go to the demo and copy paste manually.

**Comment by royboy789** [comment]
You have to run npm install to get gulp then run `gulp` so that it builds out all the files into the build directory.

**Comment by royboy789** [comment]
Sorry its `gulp init` that you need to run first, then `gulp` as you make changes to sass or js

**Comment by dgitaldesignco** [comment]
Thank you! <3
