### ISSUE TITLE
Install issue white screen of death.

### ISSUE THREAD

**Issue by strohy85** [royboy789/Angular-Wordpress-Theme#17]
Got this issue on install. 

Fatal error: Call to undefined function rest_get_url_prefix() in wp-content/themes/Angular-Wordpress-Theme-master/inc/angular-enqueue.php on line 23

**Comment by royboy789** [comment]
@strohy85 are you using WP API v2?

**Comment by strohy85** [comment]
Whoops missed the v2. Thanks
