### ISSUE TITLE
Error: [$injector:modulerr] 

### ISSUE THREAD

**Issue by kidnapkin** [royboy789/Angular-Wordpress-Theme#20]
right after install theme throws the error to the console:
angular-resource.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=wpAngularTheme&p1=E…2FAngular%2520Wordpress%2520Theme%2Fbuild%2Fjs%2Fangular.min.js%3A33%3A463)

**Comment by royboy789** [comment]
I'll take a look.. could be an issue with something being moved around

**Comment by Apostata** [comment]
Hi guys, in my case in the line:
wpAng.app = angular.module('wpAngularTheme',['ui.router','ngResource','ui.tinymce'])
I just removed the 'ui.tinymce'
best regards

**Comment by royboy789** [comment]
closed - angular ui moved where the minified version was in the node_modules, breaking the reference point in he gulp - download the new gulpFile.js and run `gulp init`
