### ISSUE TITLE
Wp rewrites angular routes when htmlMode(true) and refresh the page!

### ISSUE THREAD

**Issue by Apostata** [royboy789/Angular-Wordpress-Theme#21]
I'm using xampp in a virtualhost: http://virtualideas.local.
when I put the $locationProvider.html5Mode(true), works fine, but when I refresh the page, the wordpress rewrites the route, sending to a permalink version.
sample: 
virtualideas.local/post/another-posts-to-test-angularjs/ - works fine when comes from index.php
but when I refresh the page wp rewrites to virtualideas.local/another-posts-to-test-angularjs/  - and doesn't load nothing.
There is a way to solve this?
thanks in advance.

**Comment by royboy789** [comment]
I don't think this is an issue with this theme, its an issue with WP. I think there are fixes out there, but I haven't tried using it myself yet.. if you find a fix, please create a PR!

**Comment by Apostata** [comment]
Hi, Roy.

Thanks for the feedback.

Sorry to posts this as a issue.

I don’t think that is a template’s error or issue, but as you’re an expert in this matter, I thought you could help me, as I’m new to the github, I didn’t know how to send you my doubts.

Thanks for your time and for your knowledge, and sorry for the english.

Best Regards,

 

Rene Souza

 

 

De: Roy Sivan [mailto:notifications@github.com] 
Enviada em: sábado, 9 de abril de 2016 20:35
Para: royboy789/Angular-Wordpress-Theme <Angular-Wordpress-Theme@noreply.github.com>
Cc: Rene Souza <rene.souza@gmail.com>
Assunto: Re: [royboy789/Angular-Wordpress-Theme] Wp rewrites angular routes when htmlMode(true) and refresh the page! (#21)

 

I don't think this is an issue with this theme, its an issue with WP. I think there are fixes out there, but I haven't tried using it myself yet.. if you find a fix, please create a PR!
