### ISSUE TITLE
How to add Contact form or any wordpress plugin

### ISSUE THREAD

**Issue by vivekr4u** [royboy789/Angular-Wordpress-Theme#22]
Hi,

I was working on this theme. 

I was wondering how to add contact form 7 or any slider plugin which I installed on my wordpress .

Please guide us.

Thanks and regards

Vivek

**Comment by royboy789** [comment]
You have to build it into the theme, since this theme doesn't really deploy or make use of shortcodes, it is a development boilerplate to start building a custom theme.
