### ISSUE TITLE
slug routing

### ISSUE THREAD

**Issue by berendvaneerde** [royboy789/Angular-Wordpress-Theme#5]
Hi Roy,

Very exited about this combination. Especially to upgrade some of my old wordpress sites with angular. A workflow I am loving more and more. 

Currently the theme routes to the id of a post. Do you see any possibility to use the slug of wordpress posts as a routing. So that one can get some prettier URL's and also manually adjust them by adjusting slug.

**Comment by royboy789** [comment]
Woah, sorry I did not see this! have you gotten it to work? I can get it working and push it. Requires some  $location logic

**Comment by berendvaneerde** [comment]
I just got slug routing working on a mean stack, but not on the wordpress theme. Would be great if you could implement it. I'm kind of new to this...

**Comment by royboy789** [comment]
slug routing now part of the theme. Had to create a new route to pass back the ID, and so not as to disturb the template file, had to do another get request to WP-API. Will try to combine in my next pass
