### ISSUE TITLE
WP-API 2 Refactor

### ISSUE THREAD

**Issue by klihelp** [royboy789/Angular-Wordpress-Theme#8]
```
rest_get_url_prefix()
```

**Comment by royboy789** [comment]
Leaving open as WP-API 2 conversion

**Comment by royboy789** [comment]
sorry for all the name changes, was going to make this a parent / catch-all task, but that is what the new milestone is for.

**Comment by klihelp** [comment]
eg. posts url would be: 
`rest_get_url_prefix() . '/v2/wp/posts/`

**Comment by royboy789** [comment]
fixed in v6 merge 4e50208ca34383009ec28d42ce0b71fd84841647
